spring:
  datasource:
    url: jdbc:mysql://database-1.cvnar0hplnwz.ap-northeast-2.rds.amazonaws.com:3306/blamarket?autoReconnect=true
    username: admin
    password: rkddkwl1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: test
      password: test


logging.level.org:
  springframework: info
  springframework.web: info