spring:
  datasource:
    url: jdbc:mysql://database-1.cvnar0hplnwz.ap-northeast-2.rds.amazonaws.com:3306/blamarket?autoReconnect=true
    username: admin
    password: rkddkwl1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
  security:
    user:
      name: test
      password: test

  redis:
    host: 121.140.253.36
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: yoonsucker@gmail.com
    password: gvcuihfzwolriatb
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true


logging.level.org:
  springframework: info
  springframework.web: info